language: node_js

os:
    - linux
    - osx
    - windows

node_js:
  - "8"
  - "10"
  - "12"
  - "node"

sudo: false

before_install:
  - "node `npm prefix -g`/node_modules/npm/bin/npm-cli.js i -g npm@latest"

install:
  - "npm install"

os:
  - "linux"
  - "osx"
  - "windows"
