language: node_js

os:
    - linux
    - osx
    - windows

node_js:
  - "8"
  - "10"
  - "12"
  - "node"

sudo: false

before_install:
  - "npm update -g npm"

install:
  - "npm install"

os:
  - "linux"
  - "osx"
  - "windows"
