language: node_js

os:
    - linux
    - osx
    - windows

node_js:
  - "8"
  - "10"
  - "12"
  - "node"

sudo: false

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export NPM_CONFIG_PREFIX=c:\\npm_prefix PATH="/c/npm_prefix:$PATH"; fi
  - "npm update -g npm"

install:
  - "npm install"

os:
  - "linux"
  - "osx"
  - "windows"
